title: "NY.S 연구 블로그"
description: "Drone · PX4 · ROS2 · AI 연구 기록"
url: "https://sung-nakyeong.github.io"
baseurl: ""    # 개인 사이트는 빈 값
locale: "ko-KR"

# Minimal Mistakes 테마(가장 대중적)
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"   # "dark", "air", "neon" 등 취향대로

# GitHub Pages에서 허용되는 플러그인
plugins:
  - jekyll-include-cache
  - jekyll-paginate

# 글 목록 페이지네이션(선택)
paginate: 5
paginate_path: "/page:num/"

author:
  name: "Sung Nakyeong"
  avatar: "/assets/images/profile.png"
  bio: "Ph.D student · Drone AI"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Sung-Nakyeong"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"   # 아이콘이 안 보이면 label만 써도 됩니다
      url: "https://scholar.google.com/"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your.name@domain.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/"


# 기본 레이아웃/옵션(글에 자동 적용)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# 개별 페이지용 디렉토리 사용
include:
  - _pages

# 네비게이션(헤더 메뉴)
collections: {}
